/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         name: "enterprise-customer"
 *     }
 */
export interface GroupUpdateParams {
    /** Human-readable name for the group, used for display and organization */
    name: string;
}
