/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         value: "Your updated balance is {balance}",
 *         fields: [{
 *                 name: "balance",
 *                 description: "Updated account balance",
 *                 examples: ["10000"]
 *             }]
 *     }
 */
export interface UtteranceUpdateParams {
    /** The textual content of the utterance. */
    value?: string;
    /** A sequence of utterance fields associated with the utterance. */
    fields?: Parlant.UtteranceField[];
    tags?: Parlant.UtteranceTagUpdateParams;
}
