/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         value: "Your account balance is {balance}",
 *         fields: [{
 *                 name: "balance",
 *                 description: "Account's balance",
 *                 examples: ["9000"]
 *             }]
 *     }
 */
export interface UtteranceCreationParams {
    /** The textual content of the utterance. */
    value: string;
    /** A sequence of utterance fields associated with the utterance. */
    fields: Parlant.UtteranceField[];
    /** Collection of tag IDs associated with the utterance. */
    tags?: string[];
}
