/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         kind: Parlant.ToolServiceKindDto.Sdk
 *     }
 */
export interface ServiceUpdateParams {
    kind: Parlant.ToolServiceKindDto;
    sdk?: Parlant.SdkServiceParams;
    openapi?: Parlant.OpenApiServiceParams;
}
