/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateCustomerRequestExtraValue } from "../../types/CreateCustomerRequestExtraValue";
export declare const CreateCustomerRequest: core.serialization.Schema<serializers.CreateCustomerRequest.Raw, Parlant.CreateCustomerRequest>;
export declare namespace CreateCustomerRequest {
    interface Raw {
        name: string;
        extra?: Record<string, CreateCustomerRequestExtraValue.Raw | null | undefined> | null;
    }
}
