/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
export const CustomerCreationParams = core.serialization.object({
    name: core.serialization.string(),
    extra: core.serialization.record(core.serialization.string(), core.serialization.string().optional()).optional(),
});
