/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { ExtraUpdate } from "../../../../types/ExtraUpdate";
import { TagsUpdate } from "../../../../types/TagsUpdate";
export declare const UpdateCustomerRequest: core.serialization.Schema<serializers.UpdateCustomerRequest.Raw, Parlant.UpdateCustomerRequest>;
export declare namespace UpdateCustomerRequest {
    interface Raw {
        name?: string | null;
        extra?: ExtraUpdate.Raw | null;
        tags?: TagsUpdate.Raw | null;
    }
}
