/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Rules {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Rules {
    protected readonly _options: Rules.Options;
    constructor(_options: Rules.Options);
    /**
     * Lists all rules for the specified group or all rules if no group is provided.
     *
     * Returns an empty list if no rules exist.
     * Rules are returned in no guaranteed order.
     * Does not include relationships or tool associations.
     *
     * @param {Parlant.RulesListRequest} request
     * @param {Rules.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.rules.list()
     */
    list(request?: Parlant.RulesListRequest, requestOptions?: Rules.RequestOptions): Promise<Parlant.Rule[]>;
    /**
     * Creates a new rule.
     *
     * The rule will be initialized with the provided condition and optional action and settings.
     * A unique identifier will be automatically generated unless a custom ID is provided.
     *
     * See the [documentation](https://parlant.io/docs/concepts/customization/rules) for more information.
     *
     * @param {Parlant.RuleCreationParams} request
     * @param {Rules.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.rules.create({
     *         condition: "when the customer asks about pricing",
     *         action: "provide current pricing information and mention any ongoing promotions",
     *         metadata: {
     *             "key1": "value1",
     *             "key2": "value2"
     *         },
     *         enabled: false,
     *         compositionMode: "strict_canned",
     *         effort: "high",
     *         labels: ["vip", "priority"]
     *     })
     */
    create(request: Parlant.RuleCreationParams, requestOptions?: Rules.RequestOptions): Promise<Parlant.Rule>;
    /**
     * Retrieves a specific rule with all its relationships and tool associations.
     *
     * Returns both direct and indirect relationships between rules.
     * Tool associations indicate which tools the rule can use.
     *
     * @param {string} ruleId - Unique identifier for the rule
     * @param {Rules.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.rules.retrieve("IUCGT-l4pS")
     */
    retrieve(ruleId: string, requestOptions?: Rules.RequestOptions): Promise<Parlant.RuleWithRelationshipsAndToolAssociations>;
    /**
     * @param {string} ruleId - Unique identifier for the rule
     * @param {Rules.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.rules.delete("IUCGT-l4pS")
     */
    delete(ruleId: string, requestOptions?: Rules.RequestOptions): Promise<void>;
    /**
     * Updates a rule's relationships and tool associations.
     *
     * Only provided attributes will be updated; others remain unchanged.
     *
     * Relationship rules:
     * - A rule cannot relate to itself
     * - Only direct relationships can be removed
     * - The relationship must specify this rule as source or target
     *
     * Tool Association rules:
     * - Tool services and tools must exist before creating associations
     *
     * Action with text can not be updated to None.
     *
     * @param {string} ruleId - Unique identifier for the rule
     * @param {Parlant.RuleUpdateParams} request
     * @param {Rules.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.rules.update("IUCGT-l4pS", {
     *         condition: "when the customer asks about pricing",
     *         action: "provide current pricing information",
     *         toolAssociations: {
     *             add: [{
     *                     serviceName: "new_service",
     *                     toolName: "new_tool"
     *                 }],
     *             remove: [{
     *                     serviceName: "old_service",
     *                     toolName: "old_tool"
     *                 }]
     *         },
     *         enabled: true,
     *         metadata: {
     *             set: {
     *                 "key1": "value1",
     *                 "key2": "value2"
     *             },
     *             unset: ["key3", "key4"]
     *         },
     *         effort: "high"
     *     })
     */
    update(ruleId: string, request?: Parlant.RuleUpdateParams, requestOptions?: Rules.RequestOptions): Promise<Parlant.RuleWithRelationshipsAndToolAssociations>;
}
