/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { TrainingCreationParams } from "../../../types/TrainingCreationParams";
export declare const Request: core.serialization.Schema<serializers.train.create.Request.Raw, Parlant.TrainingCreationParams | undefined>;
export declare namespace Request {
    type Raw = TrainingCreationParams.Raw | null | undefined;
}
