/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
export const TermUpdateParams = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    synonyms: core.serialization.list(core.serialization.string()).optional(),
});
