/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
export const TermCreationParams = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string(),
    synonyms: core.serialization.list(core.serialization.string()).optional(),
});
