/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         title: "Customer Onboarding",
 *         description: "1. Customer wants to lock their card\n2. Customer reports that their card doesn't work\n3. Customer suspects their card has been stolen",
 *         conditions: ["customer needs unlocking their card", "customer needs help with card"],
 *         tags: ["tag1", "tag2"]
 *     }
 */
export interface JourneyCreationParams {
    /** The title of the journey */
    title: string;
    description: string;
    conditions: string[];
    /** List of tag IDs associated with the journey */
    tags?: string[];
}
