"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Request = void 0;
const CreateAgentRequest_1 = require("../types/CreateAgentRequest");
exports.Request = CreateAgentRequest_1.CreateAgentRequest.optional();
