/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { ContextVariable } from "../../../types/ContextVariable";
export const Response = core.serialization.list(ContextVariable);
