/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface TagCreationParams {
    /** Name of the tag */
    name: string;
}
