/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
export declare class ConflictError extends errors.ParlantError {
    constructor(body?: unknown);
}
