/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const GroupUpdateParams: core.serialization.Schema<serializers.GroupUpdateParams.Raw, Parlant.GroupUpdateParams>;
export declare namespace GroupUpdateParams {
    interface Raw {
        name: string;
    }
}
