/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const GroupCreationParams: core.serialization.Schema<serializers.GroupCreationParams.Raw, Parlant.GroupCreationParams>;
export declare namespace GroupCreationParams {
    interface Raw {
        name: string;
    }
}
