/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         condition: "when the customer asks about pricing",
 *         action: "provide current pricing information and mention any ongoing promotions",
 *         metadata: {
 *             "key1": "value1",
 *             "key2": "value2"
 *         },
 *         enabled: false
 *     }
 */
export interface GuidelineCreationParams {
    /** If this condition is satisfied, the action will be performed */
    condition: string;
    /** This action will be performed if the condition is satisfied */
    action: string;
    /** Metadata for the guideline */
    metadata?: Record<string, unknown>;
    /** Whether the guideline is enabled */
    enabled?: boolean;
    /** The tags associated with the guideline */
    tags?: string[];
}
