/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         invoices: [{
 *                 payload: {
 *                     kind: "guideline"
 *                 },
 *                 checksum: "checksum",
 *                 approved: true
 *             }]
 *     }
 */
export interface GuidelineCreationParams {
    /** A collection of invoices obtained from evaluating guidelines */
    invoices: Parlant.Invoice[];
}
