/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { CriticalityDto } from "../../../../types/CriticalityDto";
import { RuleToolAssociationUpdateParams } from "../../../../types/RuleToolAssociationUpdateParams";
import { RuleGroupsUpdateParams } from "../../../../types/RuleGroupsUpdateParams";
import { RuleMetadataUpdateParams } from "../../../../types/RuleMetadataUpdateParams";
import { CompositionModeDto } from "../../../../types/CompositionModeDto";
import { EffortDto } from "../../../../types/EffortDto";
import { RuleLabelsUpdateParams } from "../../../../types/RuleLabelsUpdateParams";
export declare const RuleUpdateParams: core.serialization.Schema<serializers.RuleUpdateParams.Raw, Parlant.RuleUpdateParams>;
export declare namespace RuleUpdateParams {
    interface Raw {
        condition?: string | null;
        action?: string | null;
        description?: string | null;
        title?: string | null;
        criticality?: CriticalityDto.Raw | null;
        tool_associations?: RuleToolAssociationUpdateParams.Raw | null;
        enabled?: boolean | null;
        groups?: RuleGroupsUpdateParams.Raw | null;
        metadata?: RuleMetadataUpdateParams.Raw | null;
        composition_mode?: CompositionModeDto.Raw | null;
        effort?: EffortDto.Raw | null;
        labels?: RuleLabelsUpdateParams.Raw | null;
        priority?: number | null;
        signals?: string[] | null;
        anti_signals?: string[] | null;
    }
}
