/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { CriticalityDto } from "../../../../types/CriticalityDto";
import { CompositionModeDto } from "../../../../types/CompositionModeDto";
import { EffortDto } from "../../../../types/EffortDto";
export declare const RuleCreationParams: core.serialization.Schema<serializers.RuleCreationParams.Raw, Parlant.RuleCreationParams>;
export declare namespace RuleCreationParams {
    interface Raw {
        id?: string | null;
        condition: string;
        action?: string | null;
        description?: string | null;
        title?: string | null;
        criticality?: CriticalityDto.Raw | null;
        metadata?: Record<string, unknown> | null;
        enabled?: boolean | null;
        groups?: string[] | null;
        composition_mode?: CompositionModeDto.Raw | null;
        effort?: EffortDto.Raw | null;
        track?: boolean | null;
        labels?: string[] | null;
        priority?: number | null;
        signals?: string[] | null;
        anti_signals?: string[] | null;
    }
}
