/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
import { EventKindDto } from "../../../../types/EventKindDto";
import { EventSourceDto } from "../../../../types/EventSourceDto";
export const EventCreationParams = core.serialization.object({
    kind: EventKindDto,
    source: EventSourceDto,
    data: core.serialization.string().optional(),
});
