/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
export const SessionCreationParams = core.serialization.object({
    agentId: core.serialization.property("agent_id", core.serialization.string()),
    customerId: core.serialization.property("customer_id", core.serialization.string().optional()),
    title: core.serialization.string().optional(),
});
