/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
import { ConsumptionOffsetsUpdateParams } from "../../../../types/ConsumptionOffsetsUpdateParams";
export const SessionUpdateParams = core.serialization.object({
    consumptionOffsets: core.serialization.property("consumption_offsets", ConsumptionOffsetsUpdateParams.optional()),
    title: core.serialization.string().optional(),
});
