/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../index";
import * as Parlant from "../../../api/index";
import * as core from "../../../core";
import { EventKindDto } from "../../types/EventKindDto";
import { EventSourceDto } from "../../types/EventSourceDto";
export declare const CreateEventRequest: core.serialization.Schema<serializers.CreateEventRequest.Raw, Omit<Parlant.CreateEventRequest, "moderation">>;
export declare namespace CreateEventRequest {
    interface Raw {
        kind: EventKindDto.Raw;
        source: EventSourceDto.Raw;
        content: string;
    }
}
