/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../index";
import * as Parlant from "../../../api/index";
import * as core from "../../../core";
import { GuidelinePayload } from "../../types/GuidelinePayload";
export declare const CreateEvaluationRequest: core.serialization.Schema<serializers.CreateEvaluationRequest.Raw, Parlant.CreateEvaluationRequest>;
export declare namespace CreateEvaluationRequest {
    interface Raw {
        agent_id: string;
        payloads: GuidelinePayload.Raw[];
    }
}
