/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../index";
import * as Parlant from "../../../api/index";
import * as core from "../../../core";
import { ConsumptionOffsetsPatch } from "../../types/ConsumptionOffsetsPatch";
export declare const PatchSessionRequest: core.serialization.Schema<serializers.PatchSessionRequest.Raw, Parlant.PatchSessionRequest>;
export declare namespace PatchSessionRequest {
    interface Raw {
        consumption_offsets?: ConsumptionOffsetsPatch.Raw | null;
        title?: string | null;
    }
}
