/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../index";
import * as Parlant from "../../../api/index";
import * as core from "../../../core";
import { Data } from "../../types/Data";
export declare const UpdateContextVariableValueRequest: core.serialization.Schema<serializers.UpdateContextVariableValueRequest.Raw, Parlant.UpdateContextVariableValueRequest>;
export declare namespace UpdateContextVariableValueRequest {
    interface Raw {
        data: Data.Raw;
    }
}
