/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
import { ToolServiceKindDto } from "../../../../types/ToolServiceKindDto";
import { SdkServiceParams } from "../../../../types/SdkServiceParams";
import { OpenApiServiceParams } from "../../../../types/OpenApiServiceParams";
export const ServiceUpdateParams = core.serialization.object({
    kind: ToolServiceKindDto,
    sdk: SdkServiceParams.optional(),
    openapi: OpenApiServiceParams.optional(),
});
