/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         endUserId: "end_user_id",
 *         agentId: "agent_id"
 *     }
 */
export interface CreateSessionRequest {
    allowGreeting?: boolean;
    endUserId: string;
    agentId: string;
    title?: string;
}
