/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         kind: "message",
 *         source: "customer"
 *     }
 */
export interface EventCreationParams {
    moderation?: Parlant.Moderation;
    kind: Parlant.EventKindDto;
    source: Parlant.EventSourceDto;
    data?: string;
}
