/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         minOffset: 0,
 *         traceId: "corr_13xyz",
 *         kinds: "message,tool"
 *     }
 */
export interface SessionsListEventsRequest {
    minOffset?: number;
    source?: Parlant.EventSourceDto;
    traceId?: string;
    kinds?: string;
    waitForData?: number;
}
