/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface SessionsListRequest {
    /**
     * Unique identifier of the agent
     */
    agentId?: string;
    /**
     * Unique identifier of the customers
     */
    customerId?: string;
}
