/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         agentId: "agent_id"
 *     }
 */
export interface SessionCreationParams {
    allowGreeting?: boolean;
    agentId: string;
    customerId?: string;
    title?: string;
}
