/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {}
 */
export interface SessionUpdateParams {
    consumptionOffsets?: Parlant.ConsumptionOffsetsUpdateParams;
    title?: string;
}
