/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         consumptionOffsets: {
 *             client: 42
 *         },
 *         title: "Updated session title"
 *     }
 */
export interface SessionUpdateParams {
    consumptionOffsets?: Parlant.ConsumptionOffsetsUpdateParams;
    /** Descriptive title for the session */
    title?: string;
    /** The mode of the session, either 'auto' or 'manual'. In manual mode, events added to a session will not be responded to automatically by the agent. */
    mode?: Parlant.SessionModeDto;
}
