/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         agentId: "ag_123xyz",
 *         customerId: "cust_123xy"
 *     }
 */
export interface SessionsListRequest {
    agentId?: string;
    customerId?: string;
}
