/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Train {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Train {
    protected readonly _options: Train.Options;
    constructor(_options: Train.Options);
    /**
     * Starts a background training run.
     *
     * Trains every agent by default, or only the agents named in ``agent_ids``.
     * Returns immediately with the new job, whose progress can be polled via
     * ``GET /train/{job_id}``.
     *
     * @param {Parlant.TrainingCreationParams} request
     * @param {Train.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.train.create(undefined)
     */
    create(request?: Parlant.TrainingCreationParams, requestOptions?: Train.RequestOptions): Promise<Parlant.TrainingJob>;
    /**
     * Retrieves the current status and progress of a training job.
     *
     * @param {string} jobId - Unique identifier of the training job
     * @param {Train.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.train.retrieve("job_id")
     */
    retrieve(jobId: string, requestOptions?: Train.RequestOptions): Promise<Parlant.TrainingJob>;
}
