/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { Session } from "../../../types/Session";
export const Response = core.serialization.list(Session);
