/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { GuidelineConnectionUpdateParams } from "../../../../types/GuidelineConnectionUpdateParams";
import { GuidelineToolAssociationUpdateParams } from "../../../../types/GuidelineToolAssociationUpdateParams";
export declare const GuidelineUpdateParams: core.serialization.Schema<serializers.GuidelineUpdateParams.Raw, Parlant.GuidelineUpdateParams>;
export declare namespace GuidelineUpdateParams {
    interface Raw {
        connections?: GuidelineConnectionUpdateParams.Raw | null;
        tool_associations?: GuidelineToolAssociationUpdateParams.Raw | null;
    }
}
