/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { Guideline } from "../../../types/Guideline";
export const Response = core.serialization.list(Guideline);
