/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing agent's groups.
 */
export interface AgentGroupUpdateParams {
    /** List of group IDs to add to the agent */
    add?: string[];
    /** List of group IDs to remove from the agent */
    remove?: string[];
}
