/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An agent is a specialized AI personality crafted for a specific service role.
 *
 * Agents form the basic unit of conversational customization: all behavioral configurations
 * are made at the agent level.
 *
 * Use this model for representing complete agent information in API responses.
 */
export interface Agent {
    /** Unique identifier for the agent */
    id: string;
    /** The display name of the agent, mainly for management purposes */
    name: string;
    /** Optional detailed description of the agent's purpose and capabilities */
    description?: string;
    /** UTC timestamp of when the agent was created */
    creationUtc: Date;
    /** Maximum number of processing iterations the agent can perform per request */
    maxEngineIterations?: number;
}
