/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Agent {
    id: string;
    name: string;
    description?: string;
    creationUtc: Date;
    maxEngineIterations: number;
}
