/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a canned response's groups.
 *
 * Allows adding new groups to and removing existing groups from a canned response.
 * Both operations can be performed in a single request.
 */
export interface CannedResponseGroupUpdateParams {
    /** Optional collection of group ids to add to the canned response's groups */
    add?: string[];
    /** Optional collection of group ids to remove from the canned response's groups */
    remove?: string[];
}
