/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing capability's groups.
 */
export interface CapabilityGroupUpdateParams {
    /** List of group IDs to add to the capability */
    add?: string[];
    /** List of group IDs to remove from the capability */
    remove?: string[];
}
