/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Potential contradiction found between guidelines
 */
export interface CoherenceCheck {
    kind: Parlant.CoherenceCheckKindDto;
    first: Parlant.GuidelineContent;
    second: Parlant.GuidelineContent;
    /** Description of the contradiction or conflict between Guidelines */
    issue: string;
    /** Numerical rating of the contradiction's severity (1-10, where 10 is most severe) */
    severity: number;
}
