/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const CoherenceCheckKindDto = {
    ContradictionWithExistingGuideline: "contradiction_with_existing_guideline",
    ContradictionWithAnotherEvaluatedGuideline: "contradiction_with_another_evaluated_guideline",
};
