"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompositionModeDto = void 0;
exports.CompositionModeDto = {
    Fluid: "fluid",
    StrictAssembly: "strict_assembly",
    CompositedAssembly: "composited_assembly",
    FluidAssembly: "fluid_assembly",
};
