/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Defines the composition mode for an entity.
 *
 * Available options:
 * - fluid
 * - strict_assembly
 * - composited_assembly
 * - fluid_assembly
 */
export declare type CompositionModeDto = "fluid" | "strict_assembly" | "composited_assembly" | "fluid_assembly";
export declare const CompositionModeDto: {
    readonly Fluid: "fluid";
    readonly StrictAssembly: "strict_assembly";
    readonly CompositedAssembly: "composited_assembly";
    readonly FluidAssembly: "fluid_assembly";
};
