/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type ConnectionKindDto = "entails" | "suggests";
export declare const ConnectionKindDto: {
    readonly Entails: "entails";
    readonly Suggests: "suggests";
};
