"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConnectionPropositionKindDto = void 0;
exports.ConnectionPropositionKindDto = {
    ConnectionWithExistingGuideline: "connection_with_existing_guideline",
    ConnectionWithAnotherEvaluatedGuideline: "connection_with_another_evaluated_guideline",
};
