/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface ConnectionProposition {
    checkKind: Parlant.ConnectionPropositionKindDto;
    source: Parlant.GuidelineContent;
    target: Parlant.GuidelineContent;
    connectionKind: Parlant.ConnectionKindDto;
}
