/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const ConnectionPropositionKindDto = {
    ConnectionWithExistingGuideline: "connection_with_existing_guideline",
    ConnectionWithAnotherEvaluatedGuideline: "connection_with_another_evaluated_guideline",
};
