/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ContextVariableAndValue {
    id: string;
    name: string;
    description: string;
    key: string;
    value?: unknown;
}
