/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface CreateServiceResponse {
    name: string;
    kind: Parlant.ToolServiceKindDto;
    url: string;
}
