/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a customer's extra metadata.
 */
export interface CustomerExtraUpdateParams {
    /** Key-value pairs (`str: str`) to describe the customer */
    add?: Record<string, string | undefined>;
    /** Extra Metadata keys to remove */
    remove?: string[];
}
