/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a customer's groups.
 *
 * Allows adding new groups to and removing existing groups from a customer.
 * Both operations can be performed in a single request.
 */
export interface CustomerGroupUpdateParams {
    /** Optional collection of group ids to add to the customer's groups */
    add?: string[];
    /** Optional collection of group ids to remove from the customer's groups */
    remove?: string[];
}
