/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a customer's extra metadata.
 *
 * Optional:
 * add: Dictionary of new or updated key-value pairs
 * remove: List of keys to remove from extra metadata
 */
export interface CustomerExtraUpdateParams {
    add?: Record<string, string | undefined>;
    remove?: string[];
}
