/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Defines how much effort the agent invests in processing.
 *
 * Available options:
 * - min
 * - low
 * - medium
 * - high
 * - max
 */
export type EffortDto = "min" | "low" | "medium" | "high" | "max";
export declare const EffortDto: {
    readonly Min: "min";
    readonly Low: "low";
    readonly Medium: "medium";
    readonly High: "high";
    readonly Max: "max";
};
