"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EffortDto = void 0;
exports.EffortDto = {
    Min: "min",
    Low: "low",
    Medium: "medium",
    High: "high",
    Max: "max",
};
