/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const EvaluationStatusDto = {
    Pending: "pending",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
};
