/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface Event {
    id: string;
    source: Parlant.EventSourceDto;
    kind: string;
    offset: number;
    creationUtc: Date;
    correlationId: string;
    data?: unknown;
}
