/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface EventInspectionResult {
    sessionId: string;
    event: Parlant.Event;
    trace?: Parlant.EventTrace;
}
