/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface EventTrace {
    toolCalls: Parlant.ToolCall[];
    messageGenerations: Parlant.MessageGenerationInspection[];
    preparationIterations: Parlant.PreparationIteration[];
}
