/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Result of inspecting an event.
 */
export interface EventInspectionResult {
    /** Unique identifier for the session */
    sessionId: string;
    event: Parlant.Event;
    trace?: Parlant.EventTrace;
}
