/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface ExtraUpdate {
    add?: Record<string, Parlant.ExtraUpdateDtoAddValue | undefined>;
    remove?: string[];
}
