/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a fragment's tags.
 *
 * Allows adding new tags to and removing existing tags from a fragment.
 * Both operations can be performed in a single request.
 */
export interface FragmentTagUpdateParams {
    /** Optional collection of tag ids to add to the fragment's tags */
    add?: string[];
    /** Optional collection of tag ids to remove from the fragment's tags */
    remove?: string[];
}
