/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface Fragment {
    /** Unique identifier for the tag */
    id: string;
    /** UTC timestamp of when the fragment was created */
    creationUtc: Date;
    /** The textual content of the fragment. */
    value: string;
    /** A sequence of fragment fields associated with the fragment. */
    fields: Parlant.FragmentField[];
    /** Collection of tag IDs associated with the fragment. */
    tags: string[];
}
