/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface FragmentField {
    /** The name of the fragment field. */
    name: string;
    /** A description of the fragment field. */
    description: string;
    examples: string[];
}
