/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Rules for validating data freshness.
 */
export interface FreshnessRules {
    /** List of valid months (1-12) */
    months?: number[];
    /** List of valid days of month (1-31) */
    daysOfMonth?: number[];
    /** List of valid days of week */
    daysOfWeek?: Parlant.DayOfWeekDto[];
    /** List of valid hours (0-23) */
    hours?: number[];
    /** List of valid minutes (0-59) */
    minutes?: number[];
    /** List of valid seconds (0-59) */
    seconds?: number[];
}
