/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface GenerationInfo {
    schemaName: string;
    model: string;
    duration: number;
    usage: Parlant.UsageInfo;
}
