/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Represents a group in the system.
 *
 * Groups can be used to categorize and label various resources like customers, sessions,
 * or content. They provide a flexible way to organize and filter data.
 */
export interface Group {
    /** Unique identifier for the group */
    id: string;
    /** Human-readable name for the group, used for display and organization */
    name: string;
}
