/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents a connection between two guidelines.
 */
export interface GuidelineConnection {
    /** Unique identifier for the `GuildelineConnection` */
    id: string;
    source: Parlant.Guideline;
    target: Parlant.Guideline;
    /** `True` if there is a path from `source` to `target` but no direct connection */
    indirect: boolean;
}
