/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface GuidelineConnectionsPatch {
    add?: Parlant.GuidelineConnectionAddition[];
    remove?: string[];
}
