/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A container for the values of a Guideline's content
 */
export interface GuidelineContent {
    /** If this condition is satisfied, the action will be performed */
    condition: string;
    /** This action will be performed if the condition is satisfied */
    action: string;
}
