/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface GuidelinePropositionInspection {
    totalDuration: number;
    batches: Parlant.GenerationInfo[];
}
