/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Parameters for updaing a guideline connection.
 *
 * `add` is expected to be a collection of addition objects.
 * `remove` should contain the `id`s of the guidelines to remove.
 */
export interface GuidelineConnectionUpdateParams {
    add?: Parlant.GuidelineConnectionAddition[];
    remove?: string[];
}
