/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Represents a guideline.
 */
export interface Guideline {
    /** Unique identifier for the guideline */
    id: string;
    /** If this condition is satisfied, the action will be performed */
    condition: string;
    /** This action will be performed if the condition is satisfied */
    action: string;
    /** Whether the guideline is enabled */
    enabled: boolean;
    /** The tags associated with the guideline */
    tags: string[];
}
