/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface GuidelineWithConnectionsAndToolAssociations {
    guideline: Parlant.Guideline;
    connections: Parlant.GuidelineConnection[];
    toolAssociations: Parlant.GuidelineToolAssociation[];
}
