/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface GuidelineConnection {
    id: string;
    source: Parlant.Guideline;
    target: Parlant.Guideline;
    kind: Parlant.ConnectionKindDto;
    indirect: boolean;
}
