/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Result wrapper for Guidelines creation.
 */
export interface GuidelineCreationResult {
    items: Parlant.GuidelineWithConnectionsAndToolAssociations[];
}
