/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Result wrapped for `Guideline`s creation.
 */
export interface GuidelineCreationResult {
    /** */
    items: Parlant.GuidelineWithConnectionsAndToolAssociations[];
}
