/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Used to add connections between `Guideline`s.
 */
export interface GuidelineConnectionAddition {
    /** `id` of `Guideline` that is source of this connection. */
    source: string;
    /** `id` of `Guideline` that is target of this connection. */
    target: string;
    kind: Parlant.ConnectionKindDto;
}
