/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface GuidelinePayload {
    content: Parlant.GuidelineContent;
    operation: Parlant.GuidelinePayloadOperationDto;
    updatedId?: string;
    coherenceCheck: boolean;
    connectionProposition: boolean;
}
