/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface GuidelineInvoice {
    payload: Parlant.GuidelinePayload;
    checksum: string;
    approved: boolean;
    data: Parlant.GuidelineInvoiceData;
    error?: string;
}
