/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface Invoice {
    payload: Parlant.Payload;
    checksum: string;
    approved: boolean;
    data?: Parlant.InvoiceData;
    error?: string;
}
