/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface JourneyGraph {
    /** Unique identifier for the journey */
    id: string;
    /** The title of the journey */
    title: string;
    description: string;
    conditions: string[];
    /** List of tag IDs associated with the journey */
    tags?: string[];
    compositionMode?: Parlant.CompositionModeDto;
    nodes?: Parlant.JourneyNode[];
    edges?: Parlant.JourneyEdge[];
}
