/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface JourneyNode {
    id: string;
    creationUtc: Date;
    action?: string;
    tools?: string[];
    metadata?: Record<string, unknown>;
    description?: string;
    compositionMode?: string;
}
