/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an existing journey's triggers.
 */
export interface JourneyTriggerUpdateParams {
    /** List of rule IDs to add to the journey */
    add?: string[];
    /** List of rule IDs to remove from the journey */
    remove?: string[];
}
