/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface JourneyGraph {
    /** Unique identifier for the journey */
    id: string;
    /** The title of the journey */
    title: string;
    description: string;
    triggers: string[];
    /** List of tag IDs associated with the journey */
    tags?: string[];
    compositionMode?: Parlant.CompositionModeDto;
    /** Labels associated with the journey */
    labels?: string[];
    priority?: number;
    /** UTC timestamp of the last modification to the journey */
    lastModified: Date;
    nodes?: Parlant.JourneyNode[];
    edges?: Parlant.JourneyEdge[];
}
