/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Evaluation results for a Guideline, including contradiction checks and connection proposals
 */
export interface LegacyGuidelineInvoiceData {
    coherenceChecks: Parlant.CoherenceCheck[];
    connectionPropositions?: Parlant.ConnectionProposition[];
}
