/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Evaluation invoices to generate Guidelines from.
 */
export interface LegacyGuidelineCreationParams {
    invoices: Parlant.LegacyInvoice[];
}
