/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * A Guideline with its connections and tool associations.
 */
export interface LegacyGuidelineWithConnectionsAndToolAssociations {
    guideline: Parlant.LegacyGuideline;
    connections: Parlant.LegacyGuidelineConnection[];
    toolAssociations: Parlant.GuidelineToolAssociation[];
}
