/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface ListInteractionsResponse {
    sessionId: string;
    interactions: Parlant.Interaction[];
}
