/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Inspection data for message generation.
 */
export interface MessageGenerationInspection {
    generation: Parlant.GenerationInfo;
    /** The messages that were generated */
    messages: (string | undefined)[];
}
