/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type Moderation = "auto" | "paranoid" | "none";
export declare const Moderation: {
    readonly Auto: "auto";
    readonly Paranoid: "paranoid";
    readonly None: "none";
};
