/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Configuration for OpenAPI-based service integration
 */
export interface OpenApiServiceParams {
    /** Base URL for the service. Must include http:// or https:// scheme. */
    url: string;
    /** URL or filesystem path to the OpenAPI spec. If a URL, must be publicly accessible. For filesystem paths, the server must have read access. */
    source: string;
}
