/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface PreparationIteration {
    guidelinePropositions: Parlant.GuidelineProposition[];
    toolCalls: Parlant.ToolCall[];
    terms: Parlant.Term[];
    contextVariables: Parlant.ContextVariableAndValue[];
}
