/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A term participating in the preparation for an iteration.
 */
export interface PreparationIterationTerm {
    /** Unique identifier for the term */
    id: string;
    /** The name of the term, e.g., 'Gas' in blockchain. */
    name: string;
    /** A detailed description of the term */
    description: string;
    /** A list of synonyms for the term, including alternate contexts if applicable. */
    synonyms?: string[];
}
