/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Generation information for a preparation iteration.
 */
export interface PreparationIterationGenerations {
    guidelineMatching: Parlant.GuidelineMatchingInspection;
    /** A list of `GenerationInfoDTO` describing the executed tool calls */
    toolCalls: Parlant.GenerationInfo[];
}
