/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface ReadContextVariableResponse {
    contextVariable: Parlant.ContextVariable;
    keyValuePairs?: Record<string, Parlant.ContextVariableValue | undefined>;
}
