/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The kind of relationship.
 */
export type RelationshipKindDto = "entailment" | "priority" | "dependency" | "overlap";
export declare const RelationshipKindDto: {
    readonly Entailment: "entailment";
    readonly Priority: "priority";
    readonly Dependency: "dependency";
    readonly Overlap: "overlap";
};
