/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents an association between a Rule and a Tool, enabling automatic tool invocation
 * when the Rule's conditions are met.
 */
export interface RuleToolAssociation {
    /** Unique identifier for the association between a tool and a rule */
    id: string;
    /** Unique identifier for the rule */
    ruleId: string;
    toolId: Parlant.ToolId;
}
