/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the metadata of a rule.
 */
export interface RuleMetadataUpdateParams {
    /** Metadata for the rule */
    set?: Record<string, unknown>;
    /** Metadata keys to remove from the rule */
    unset?: string[];
}
