/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the groups of an existing rule.
 */
export interface RuleGroupsUpdateParams {
    /** List of group IDs to add to the rule */
    add?: string[];
    /** List of group IDs to remove from the rule */
    remove?: string[];
}
