/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents a rule.
 */
export interface Rule {
    /** Unique identifier for the rule */
    id: string;
    /** If this condition is satisfied, the action will be performed */
    condition: string;
    /** This action will be performed if the condition is satisfied */
    action?: string;
    /** Optional description providing additional context for the rule */
    description?: string;
    /** Optional short title for display purposes only */
    title?: string;
    /** The criticality level of the rule */
    criticality?: Parlant.CriticalityDto;
    /** Whether the rule is enabled */
    enabled?: boolean;
    /** The groups associated with the rule */
    groups: string[];
    /** Metadata for the rule */
    metadata: Record<string, unknown>;
    /** UTC timestamp of the last modification to the rule */
    modifiedUtc: Date;
    compositionMode?: Parlant.CompositionModeDto;
    effort?: Parlant.EffortDto;
    track?: boolean;
    /** The labels associated with the rule */
    labels?: string[];
    priority?: number;
    /** Signals associated with the rule, embedded as independent vectors to help with retrieval and matching. */
    signals?: string[];
    /** In-domain user messages that should not activate this rule. Used as negative examples for Compass recall training. */
    antiSignals?: string[];
}
