/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Payload data for a Rule operation
 */
export interface RulePayload {
    content: Parlant.RuleContent;
    toolIds: Parlant.ToolId[];
    operation: Parlant.RulePayloadOperationDto;
    /** Unique identifier for the rule */
    updatedId?: string;
    /** Optional short title for display purposes only */
    title?: string;
    /** Agent context to use when evaluating agent-dependent propositions such as rule signals. */
    agentId?: string;
    /** Whether the action proposition is enabled */
    actionProposition?: boolean;
    /** Properties proposition */
    propertiesProposition?: boolean;
    /** Journey step proposition */
    journeyNodeProposition?: boolean;
    /** Signals proposition */
    signalProposition?: boolean;
    /** Title proposition */
    titleProposition?: boolean;
}
