/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * A Rule with its relationships and tool associations.
 */
export interface RuleWithRelationshipsAndToolAssociations {
    rule: Parlant.Rule;
    relationships: Parlant.Relationship[];
    toolAssociations: Parlant.RuleToolAssociation[];
}
