/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * A session represents an ongoing conversation between an agent and a customer.
 */
export interface Session {
    /** Unique identifier for the session */
    id: string;
    /** Unique identifier for the agent associated with the session. */
    agentId: string;
    /** ID of the customer associated with this session. */
    customerId: string;
    /** UTC timestamp of when the session was created */
    creationUtc: Date;
    /** Optional descriptive title for the session */
    title?: string;
    consumptionOffsets: Parlant.ConsumptionOffsets;
}
