/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating a customer's tags.
 *
 * Optional:
 * add: List of tag IDs to add to the customer
 * remove: List of tag IDs to remove from the customer
 */
export interface TagsUpdateParams {
    add?: string[];
    remove?: string[];
}
