/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating the groups of an existing glossary term.
 */
export interface TermGroupsUpdateParams {
    /** List of group IDs to add to the term */
    add?: string[];
    /** List of group IDs to remove from the term */
    remove?: string[];
}
