/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Result from a tool execution.
 */
export interface ToolResult {
    data?: unknown;
    /** A `dict` of the metadata associated with the tool's execution */
    metadata: Record<string, unknown>;
}
