/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the tool parameter.
 */
export declare type ToolParameterTypeDto = "string" | "number" | "integer" | "boolean";
export declare const ToolParameterTypeDto: {
    readonly String: "string";
    readonly Number: "number";
    readonly Integer: "integer";
    readonly Boolean: "boolean";
};
