/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
/**
 * Represents a single function provided by a service that agents can use.
 */
export interface Tool {
    /** UTC timestamp of when the tool was created */
    creationUtc: Date;
    /** User assigned name of the tool */
    name: string;
    /** The description text of the tool */
    description: string;
    /** A `dict` of parameters passed to the tool */
    parameters: Record<string, Parlant.ToolParameter>;
    /** Names of parameters that must be provided. Optional parameters may be omitted. */
    required: string[];
}
