/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface ToolCall {
    toolId: string;
    arguments: Record<string, unknown>;
    result: Parlant.ToolResult;
}
