/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type ToolServiceKindDto = "sdk" | "openapi";
export declare const ToolServiceKindDto: {
    readonly Sdk: "sdk";
    readonly Openapi: "openapi";
};
