/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of service integration to use.
 *
 * SDK services allow bidirectional communication and streaming results.
 * OpenAPI services are simpler to integrate but only support request/response patterns.
 */
export declare type ToolServiceKindDto = "sdk" | "openapi";
export declare const ToolServiceKindDto: {
    readonly Sdk: "sdk";
    readonly Openapi: "openapi";
};
