/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface TrainingJob {
    /** Unique identifier of the training job */
    id: string;
    /** Current status of the training job */
    status: Parlant.TrainingStatusDto;
    /** Completion percentage in the range [0, 100] */
    percentage: number;
    /** Failure reason, when status is failed */
    error?: string;
}
