/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Token usage information.
 */
export interface UsageInfo {
    /** Amount of token received from user over the session */
    inputTokens: number;
    /** Amount of token sent to user over the session */
    outputTokens: number;
    /** Extra data associated with the usage information */
    extra?: Record<string, number | undefined>;
}
