/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface UsageInfo {
    inputTokens: number;
    outputTokens: number;
    extra?: Record<string, number | undefined>;
}
