/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Parameters for updating an utterance's tags.
 *
 * Allows adding new tags to and removing existing tags from an utterance.
 * Both operations can be performed in a single request.
 */
export interface UtteranceTagUpdateParams {
    /** Optional collection of tag ids to add to the utterance's tags */
    add?: string[];
    /** Optional collection of tag ids to remove from the utterance's tags */
    remove?: string[];
}
