"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UtteranceReasonDto = void 0;
exports.UtteranceReasonDto = {
    BuyTime: "buy_time",
    FollowUp: "follow_up",
};
