/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../index";
export interface Utterance {
    /** Unique identifier for the tag */
    id: string;
    /** UTC timestamp of when the utterance was created */
    creationUtc: Date;
    /** The textual content of the utterance. */
    value: string;
    /** A sequence of utterance fields associated with the utterance. */
    fields: Parlant.UtteranceField[];
    /** Collection of tag IDs associated with the utterance. */
    tags: string[];
}
