/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         sourceRule: "gid_123",
 *         targetGroup: "tid_456",
 *         kind: "entailment"
 *     }
 */
export interface RelationshipCreationParams {
    /** Unique identifier for the rule */
    sourceRule?: string;
    /** Unique identifier for the group */
    sourceGroup?: string;
    sourceTool?: Parlant.ToolId;
    /** Unique identifier for the rule */
    targetRule?: string;
    /** Unique identifier for the group */
    targetGroup?: string;
    targetTool?: Parlant.ToolId;
    kind: Parlant.RelationshipKindDto;
    groupId?: string;
}
