/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         kind: "entailment"
 *     }
 */
export interface RelationshipsListRequest {
    /**
     * The kind of relationship to list
     */
    kind: Parlant.RelationshipKindDto;
    /**
     * Whether to include indirect relationships
     */
    indirect?: boolean;
    guidelineId?: string;
    tagId?: string;
}
