/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface CannedResponsesListRequest {
    /**
     * Filter canned responses by groups
     */
    groups?: string | string[];
}
