/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { FragmentField } from "../../../../types/FragmentField";
export declare const FragmentCreationParams: core.serialization.Schema<serializers.FragmentCreationParams.Raw, Parlant.FragmentCreationParams>;
export declare namespace FragmentCreationParams {
    interface Raw {
        value: string;
        fields: FragmentField.Raw[];
        tags?: string[] | null;
    }
}
