/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../index";
/**
 * @example
 *     {
 *         kind: Parlant.EventKindDto.Message,
 *         source: Parlant.EventSourceDto.EndUser,
 *         content: "content"
 *     }
 */
export interface CreateEventRequest {
    moderation?: Parlant.Moderation;
    kind: Parlant.EventKindDto;
    source: Parlant.EventSourceDto;
    content: string;
}
