/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface FragmentsListRequest {
    /**
     * Filter fragments by tags
     */
    tags?: string | string[];
}
