/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         value: "Your updated balance is {balance}",
 *         fields: [{
 *                 name: "balance",
 *                 description: "Updated account balance",
 *                 examples: ["10000"]
 *             }]
 *     }
 */
export interface FragmentUpdateParams {
    /** The textual content of the fragment. */
    value?: string;
    /** A sequence of fragment fields associated with the fragment. */
    fields?: Parlant.FragmentField[];
    tags?: Parlant.FragmentTagUpdateParams;
}
