/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../../core";
export const AgentUpdateParams = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    maxEngineIterations: core.serialization.property("max_engine_iterations", core.serialization.number().optional()),
});
