/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const AgentUpdateParams: core.serialization.Schema<serializers.AgentUpdateParams.Raw, Parlant.AgentUpdateParams>;
export declare namespace AgentUpdateParams {
    interface Raw {
        name?: string | null;
        description?: string | null;
        max_engine_iterations?: number | null;
    }
}
