/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { CompositionModeDto } from "../../../../types/CompositionModeDto";
import { MessageOutputModeDto } from "../../../../types/MessageOutputModeDto";
import { EffortDto } from "../../../../types/EffortDto";
import { AgentGroupUpdateParams } from "../../../../types/AgentGroupUpdateParams";
export declare const AgentUpdateParams: core.serialization.Schema<serializers.AgentUpdateParams.Raw, Parlant.AgentUpdateParams>;
export declare namespace AgentUpdateParams {
    interface Raw {
        name?: string | null;
        description?: string | null;
        max_engine_iterations?: number | null;
        composition_mode?: CompositionModeDto.Raw | null;
        message_output_mode?: MessageOutputModeDto.Raw | null;
        effort?: EffortDto.Raw | null;
        groups?: AgentGroupUpdateParams.Raw | null;
    }
}
