/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Agent } from "./Agent";
export declare const AgentListResponse: core.serialization.ObjectSchema<serializers.AgentListResponse.Raw, Parlant.AgentListResponse>;
export declare namespace AgentListResponse {
    interface Raw {
        agents: Agent.Raw[];
    }
}
