/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const AgentGroupUpdateParams: core.serialization.ObjectSchema<serializers.AgentGroupUpdateParams.Raw, Parlant.AgentGroupUpdateParams>;
export declare namespace AgentGroupUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
