/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const Agent = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    creationUtc: core.serialization.property("creation_utc", core.serialization.date()),
    maxEngineIterations: core.serialization.property("max_engine_iterations", core.serialization.number()),
});
