/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const AgentMessageRuleRationaleDto: core.serialization.Schema<serializers.AgentMessageRuleRationaleDto.Raw, Parlant.AgentMessageRuleRationaleDto>;
export declare namespace AgentMessageRuleRationaleDto {
    type Raw = "unspecified" | "buy_time" | "follow_up";
}
