/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CapabilityGroupUpdateParams: core.serialization.ObjectSchema<serializers.CapabilityGroupUpdateParams.Raw, Parlant.CapabilityGroupUpdateParams>;
export declare namespace CapabilityGroupUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
