/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CoherenceCheckKindDto: core.serialization.Schema<serializers.CoherenceCheckKindDto.Raw, Parlant.CoherenceCheckKindDto>;
export declare namespace CoherenceCheckKindDto {
    type Raw = "contradiction_with_existing_guideline" | "contradiction_with_another_evaluated_guideline";
}
