/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { CoherenceCheckKindDto } from "./CoherenceCheckKindDto";
import { GuidelineContent } from "./GuidelineContent";
export const CoherenceCheck = core.serialization.object({
    kind: CoherenceCheckKindDto,
    first: GuidelineContent,
    second: GuidelineContent,
    issue: core.serialization.string(),
    severity: core.serialization.number(),
});
