/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const CoherenceCheckKindDto = core.serialization.enum_([
    "contradiction_with_existing_guideline",
    "contradiction_with_another_evaluated_guideline",
]);
