/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const ConnectionPropositionKindDto = core.serialization.enum_(["connection_with_existing_guideline", "connection_with_another_evaluated_guideline"]);
