/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { ConnectionPropositionKindDto } from "./ConnectionPropositionKindDto";
import { GuidelineContent } from "./GuidelineContent";
import { ConnectionKindDto } from "./ConnectionKindDto";
export const ConnectionProposition = core.serialization.object({
    checkKind: core.serialization.property("check_kind", ConnectionPropositionKindDto),
    source: GuidelineContent,
    target: GuidelineContent,
    connectionKind: core.serialization.property("connection_kind", ConnectionKindDto),
});
