/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ConsumptionOffsetsPatch: core.serialization.ObjectSchema<serializers.ConsumptionOffsetsPatch.Raw, Parlant.ConsumptionOffsetsPatch>;
export declare namespace ConsumptionOffsetsPatch {
    interface Raw {
        client?: number | null;
    }
}
