/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const ConsumptionOffsetsUpdateParams = core.serialization.object({
    client: core.serialization.number().optional(),
});
