/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const ContextVariableValue = core.serialization.object({
    id: core.serialization.string(),
    lastModified: core.serialization.property("last_modified", core.serialization.date()),
    data: core.serialization.unknown(),
});
