/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ContextVariableDeletionResponse: core.serialization.ObjectSchema<serializers.ContextVariableDeletionResponse.Raw, Parlant.ContextVariableDeletionResponse>;
export declare namespace ContextVariableDeletionResponse {
    interface Raw {
        context_variable_id: string;
    }
}
