/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ContextVariable } from "./ContextVariable";
export declare const ContextVariableCreationResponse: core.serialization.ObjectSchema<serializers.ContextVariableCreationResponse.Raw, Parlant.ContextVariableCreationResponse>;
export declare namespace ContextVariableCreationResponse {
    interface Raw {
        context_variable: ContextVariable.Raw;
    }
}
