/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ContextVariableValueDtoDataItem: core.serialization.Schema<serializers.ContextVariableValueDtoDataItem.Raw, Parlant.ContextVariableValueDtoDataItem>;
export declare namespace ContextVariableValueDtoDataItem {
    type Raw = string | number | number | boolean;
}
