/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const ContextVariableAndValue = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    description: core.serialization.string(),
    key: core.serialization.string(),
    value: core.serialization.unknown(),
});
