/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ContextVariable } from "./ContextVariable";
import { ContextVariableValue } from "./ContextVariableValue";
export declare const ContextVariableReadResponse: core.serialization.ObjectSchema<serializers.ContextVariableReadResponse.Raw, Parlant.ContextVariableReadResponse>;
export declare namespace ContextVariableReadResponse {
    interface Raw {
        context_variable: ContextVariable.Raw;
        key_value_pairs?: Record<string, ContextVariableValue.Raw | null | undefined> | null;
    }
}
