/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CreateAgentRequest: core.serialization.ObjectSchema<serializers.CreateAgentRequest.Raw, Parlant.CreateAgentRequest>;
export declare namespace CreateAgentRequest {
    interface Raw {
        name: string;
        description?: string | null;
        max_engine_iterations?: number | null;
    }
}
