/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const CreateInteractionsResponse: core.serialization.ObjectSchema<serializers.CreateInteractionsResponse.Raw, Parlant.CreateInteractionsResponse>;
export declare namespace CreateInteractionsResponse {
    interface Raw {
        correlation_id: string;
    }
}
