/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolServiceKindDto } from "./ToolServiceKindDto";
export declare const CreateServiceResponse: core.serialization.ObjectSchema<serializers.CreateServiceResponse.Raw, Parlant.CreateServiceResponse>;
export declare namespace CreateServiceResponse {
    interface Raw {
        name: string;
        kind: ToolServiceKindDto.Raw;
        url: string;
    }
}
