/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Term } from "./Term";
export declare const CreateTermResponse: core.serialization.ObjectSchema<serializers.CreateTermResponse.Raw, Parlant.CreateTermResponse>;
export declare namespace CreateTermResponse {
    interface Raw {
        term: Term.Raw;
    }
}
