/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Event } from "./Event";
export declare const CreateEventResponse: core.serialization.ObjectSchema<serializers.CreateEventResponse.Raw, Parlant.CreateEventResponse>;
export declare namespace CreateEventResponse {
    interface Raw {
        event: Event.Raw;
    }
}
