/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Customer } from "./Customer";
export declare const CreateCustomerResponse: core.serialization.ObjectSchema<serializers.CreateCustomerResponse.Raw, Parlant.CreateCustomerResponse>;
export declare namespace CreateCustomerResponse {
    interface Raw {
        customer: Customer.Raw;
    }
}
