/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const DayOfWeekDto: core.serialization.Schema<serializers.DayOfWeekDto.Raw, Parlant.DayOfWeekDto>;
export declare namespace DayOfWeekDto {
    type Raw = "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday";
}
