/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const DeleteContextVariableReponse: core.serialization.ObjectSchema<serializers.DeleteContextVariableReponse.Raw, Parlant.DeleteContextVariableReponse>;
export declare namespace DeleteContextVariableReponse {
    interface Raw {
        context_variable_id: string;
    }
}
