/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const DeleteEventsResponse: core.serialization.ObjectSchema<serializers.DeleteEventsResponse.Raw, Parlant.DeleteEventsResponse>;
export declare namespace DeleteEventsResponse {
    interface Raw {
        event_ids: string[];
    }
}
