/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const DeleteTagResponse: core.serialization.ObjectSchema<serializers.DeleteTagResponse.Raw, Parlant.DeleteTagResponse>;
export declare namespace DeleteTagResponse {
    interface Raw {
        tag_id: string;
    }
}
