/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const EffortDto: core.serialization.Schema<serializers.EffortDto.Raw, Parlant.EffortDto>;
export declare namespace EffortDto {
    type Raw = "min" | "low" | "medium" | "high" | "max";
}
