/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { EvaluationStatusDto } from "./EvaluationStatusDto";
import { Invoice } from "./Invoice";
export declare const EvaluationReadResponse: core.serialization.ObjectSchema<serializers.EvaluationReadResponse.Raw, Parlant.EvaluationReadResponse>;
export declare namespace EvaluationReadResponse {
    interface Raw {
        evaluation_id: string;
        status: EvaluationStatusDto.Raw;
        progress: number;
        creation_utc: string;
        error?: string | null;
        invoices: Invoice.Raw[];
    }
}
