/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const EvaluationStatusDto = core.serialization.enum_(["pending", "running", "completed", "failed"]);
