/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const EventDeletionResponse: core.serialization.ObjectSchema<serializers.EventDeletionResponse.Raw, Parlant.EventDeletionResponse>;
export declare namespace EventDeletionResponse {
    interface Raw {
        event_ids: string[];
    }
}
