/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const EventKindDto = core.serialization.enum_(["message", "tool", "status", "custom"]);
