/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Event } from "./Event";
export declare const EventListResponse: core.serialization.ObjectSchema<serializers.EventListResponse.Raw, Parlant.EventListResponse>;
export declare namespace EventListResponse {
    interface Raw {
        session_id: string;
        events: Event.Raw[];
    }
}
