/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { EventSourceDto } from "./EventSourceDto";
export const Event = core.serialization.object({
    id: core.serialization.string(),
    source: EventSourceDto,
    kind: core.serialization.string(),
    offset: core.serialization.number(),
    creationUtc: core.serialization.property("creation_utc", core.serialization.date()),
    correlationId: core.serialization.property("correlation_id", core.serialization.string()),
    data: core.serialization.unknown(),
});
