/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const EventSourceDto = core.serialization.enum_([
    "customer",
    "customer_ui",
    "human_agent",
    "human_agent_on_behalf_of_ai_agent",
    "ai_agent",
    "system",
]);
