/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const ExtraUpdateDtoAddValue: core.serialization.Schema<serializers.ExtraUpdateDtoAddValue.Raw, Parlant.ExtraUpdateDtoAddValue>;
export declare namespace ExtraUpdateDtoAddValue {
    type Raw = string | number | number | boolean;
}
