/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const FragmentTagUpdateParams: core.serialization.ObjectSchema<serializers.FragmentTagUpdateParams.Raw, Parlant.FragmentTagUpdateParams>;
export declare namespace FragmentTagUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
