/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { FragmentField } from "./FragmentField";
export declare const Fragment: core.serialization.ObjectSchema<serializers.Fragment.Raw, Parlant.Fragment>;
export declare namespace Fragment {
    interface Raw {
        id: string;
        creation_utc: string;
        value: string;
        fields: FragmentField.Raw[];
        tags: string[];
    }
}
