/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const FragmentField: core.serialization.ObjectSchema<serializers.FragmentField.Raw, Parlant.FragmentField>;
export declare namespace FragmentField {
    interface Raw {
        name: string;
        description: string;
        examples: string[];
    }
}
