/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { DayOfWeekDto } from "./DayOfWeekDto";
export declare const FreshnessRules: core.serialization.ObjectSchema<serializers.FreshnessRules.Raw, Parlant.FreshnessRules>;
export declare namespace FreshnessRules {
    interface Raw {
        months?: number[] | null;
        days_of_month?: number[] | null;
        days_of_week?: DayOfWeekDto.Raw[] | null;
        hours?: number[] | null;
        minutes?: number[] | null;
        seconds?: number[] | null;
    }
}
