/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { UsageInfo } from "./UsageInfo";
export const GenerationInfo = core.serialization.object({
    schemaName: core.serialization.property("schema_name", core.serialization.string()),
    model: core.serialization.string(),
    duration: core.serialization.number(),
    usage: UsageInfo,
});
