/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const Group: core.serialization.ObjectSchema<serializers.Group.Raw, Parlant.Group>;
export declare namespace Group {
    interface Raw {
        id: string;
        name: string;
    }
}
