/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { GenerationInfo } from "./GenerationInfo";
export declare const GuidelineMatchingInspection: core.serialization.ObjectSchema<serializers.GuidelineMatchingInspection.Raw, Parlant.GuidelineMatchingInspection>;
export declare namespace GuidelineMatchingInspection {
    interface Raw {
        total_duration: number;
        batches: GenerationInfo.Raw[];
    }
}
