/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const GuidelineRelationshipKindDto: core.serialization.Schema<serializers.GuidelineRelationshipKindDto.Raw, Parlant.GuidelineRelationshipKindDto>;
export declare namespace GuidelineRelationshipKindDto {
    type Raw = "entailment" | "priority";
}
