/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { GuidelineWithConnectionsAndToolAssociations } from "./GuidelineWithConnectionsAndToolAssociations";
export declare const GuidelineCreationResult: core.serialization.ObjectSchema<serializers.GuidelineCreationResult.Raw, Parlant.GuidelineCreationResult>;
export declare namespace GuidelineCreationResult {
    interface Raw {
        items: GuidelineWithConnectionsAndToolAssociations.Raw[];
    }
}
