/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { GuidelineConnectionAddition } from "./GuidelineConnectionAddition";
export const GuidelineConnectionUpdateParams = core.serialization.object({
    add: core.serialization.list(GuidelineConnectionAddition).optional(),
    remove: core.serialization.list(core.serialization.string()).optional(),
});
