/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { GuidelineConnectionAddition } from "./GuidelineConnectionAddition";
export declare const GuidelineConnectionsPatch: core.serialization.ObjectSchema<serializers.GuidelineConnectionsPatch.Raw, Parlant.GuidelineConnectionsPatch>;
export declare namespace GuidelineConnectionsPatch {
    interface Raw {
        add?: GuidelineConnectionAddition.Raw[] | null;
        remove?: string[] | null;
    }
}
