/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { GuidelineConnectionAddition } from "./GuidelineConnectionAddition";
export declare const GuidelineConnectionUpdateParams: core.serialization.ObjectSchema<serializers.GuidelineConnectionUpdateParams.Raw, Parlant.GuidelineConnectionUpdateParams>;
export declare namespace GuidelineConnectionUpdateParams {
    interface Raw {
        add?: GuidelineConnectionAddition.Raw[] | null;
        remove?: string[] | null;
    }
}
