/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { GuidelineContent } from "./GuidelineContent";
import { GuidelinePayloadOperationDto } from "./GuidelinePayloadOperationDto";
export const GuidelinePayload = core.serialization.object({
    content: GuidelineContent,
    operation: GuidelinePayloadOperationDto,
    updatedId: core.serialization.property("updated_id", core.serialization.string().optional()),
    coherenceCheck: core.serialization.property("coherence_check", core.serialization.boolean()),
    connectionProposition: core.serialization.property("connection_proposition", core.serialization.boolean()),
});
