/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { Guideline } from "./Guideline";
import { GuidelineConnection } from "./GuidelineConnection";
import { GuidelineToolAssociation } from "./GuidelineToolAssociation";
export const GuidelineWithConnectionsAndToolAssociations = core.serialization.object({
    guideline: Guideline,
    connections: core.serialization.list(GuidelineConnection),
    toolAssociations: core.serialization.property("tool_associations", core.serialization.list(GuidelineToolAssociation)),
});
