/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { Guideline } from "./Guideline";
import { ConnectionKindDto } from "./ConnectionKindDto";
export const GuidelineConnection = core.serialization.object({
    id: core.serialization.string(),
    source: Guideline,
    target: Guideline,
    kind: ConnectionKindDto,
    indirect: core.serialization.boolean(),
});
