/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const GuidelineProposition = core.serialization.object({
    guidelineId: core.serialization.property("guideline_id", core.serialization.string()),
    condition: core.serialization.string(),
    action: core.serialization.string(),
    score: core.serialization.number(),
    rationale: core.serialization.string(),
});
