/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { CoherenceCheck } from "./CoherenceCheck";
import { ConnectionProposition } from "./ConnectionProposition";
export declare const GuidelineInvoiceData: core.serialization.ObjectSchema<serializers.GuidelineInvoiceData.Raw, Parlant.GuidelineInvoiceData>;
export declare namespace GuidelineInvoiceData {
    interface Raw {
        coherence_checks: CoherenceCheck.Raw[];
        connection_propositions?: ConnectionProposition.Raw[] | null;
    }
}
