/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { Payload } from "./Payload";
import { InvoiceData } from "./InvoiceData";
export const Invoice = core.serialization.object({
    payload: Payload,
    checksum: core.serialization.string(),
    approved: core.serialization.boolean(),
    data: InvoiceData.optional(),
    error: core.serialization.string().optional(),
});
