/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { CompositionModeDto } from "./CompositionModeDto";
import { JourneyNode } from "./JourneyNode";
import { JourneyEdge } from "./JourneyEdge";
export declare const JourneyGraph: core.serialization.ObjectSchema<serializers.JourneyGraph.Raw, Parlant.JourneyGraph>;
export declare namespace JourneyGraph {
    interface Raw {
        id: string;
        title: string;
        description: string;
        conditions: string[];
        tags?: string[] | null;
        composition_mode?: CompositionModeDto.Raw | null;
        nodes?: JourneyNode.Raw[] | null;
        edges?: JourneyEdge.Raw[] | null;
    }
}
