/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const JourneyTriggerUpdateParams: core.serialization.ObjectSchema<serializers.JourneyTriggerUpdateParams.Raw, Parlant.JourneyTriggerUpdateParams>;
export declare namespace JourneyTriggerUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
