/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const JourneyEdge: core.serialization.ObjectSchema<serializers.JourneyEdge.Raw, Parlant.JourneyEdge>;
export declare namespace JourneyEdge {
    interface Raw {
        id: string;
        creation_utc: string;
        source: string;
        target: string;
        condition?: string | null;
        metadata?: Record<string, unknown> | null;
    }
}
