/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const JourneyGroupUpdateParams: core.serialization.ObjectSchema<serializers.JourneyGroupUpdateParams.Raw, Parlant.JourneyGroupUpdateParams>;
export declare namespace JourneyGroupUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
