/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const JourneyNode: core.serialization.ObjectSchema<serializers.JourneyNode.Raw, Parlant.JourneyNode>;
export declare namespace JourneyNode {
    interface Raw {
        id: string;
        creation_utc: string;
        action?: string | null;
        tools?: string[] | null;
        metadata?: Record<string, unknown> | null;
        description?: string | null;
        composition_mode?: string | null;
    }
}
