/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { LegacyInvoice } from "./LegacyInvoice";
export declare const LegacyGuidelineCreationParams: core.serialization.ObjectSchema<serializers.LegacyGuidelineCreationParams.Raw, Parlant.LegacyGuidelineCreationParams>;
export declare namespace LegacyGuidelineCreationParams {
    interface Raw {
        invoices: LegacyInvoice.Raw[];
    }
}
