/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { LegacyContextVariable } from "./LegacyContextVariable";
import { ContextVariableValue } from "./ContextVariableValue";
export declare const LegacyContextVariableReadResult: core.serialization.ObjectSchema<serializers.LegacyContextVariableReadResult.Raw, Parlant.LegacyContextVariableReadResult>;
export declare namespace LegacyContextVariableReadResult {
    interface Raw {
        context_variable: LegacyContextVariable.Raw;
        key_value_pairs?: Record<string, ContextVariableValue.Raw | null | undefined> | null;
    }
}
