/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolId } from "./ToolId";
export declare const LegacyContextVariableCreationParams: core.serialization.ObjectSchema<serializers.LegacyContextVariableCreationParams.Raw, Parlant.LegacyContextVariableCreationParams>;
export declare namespace LegacyContextVariableCreationParams {
    interface Raw {
        name: string;
        description?: string | null;
        tool_id?: ToolId.Raw | null;
        freshness_rules?: string | null;
    }
}
