/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolId } from "./ToolId";
export declare const LegacyContextVariable: core.serialization.ObjectSchema<serializers.LegacyContextVariable.Raw, Parlant.LegacyContextVariable>;
export declare namespace LegacyContextVariable {
    interface Raw {
        id: string;
        name: string;
        description?: string | null;
        tool_id?: ToolId.Raw | null;
        freshness_rules?: string | null;
    }
}
