/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const LegacyTermCreationParams: core.serialization.ObjectSchema<serializers.LegacyTermCreationParams.Raw, Parlant.LegacyTermCreationParams>;
export declare namespace LegacyTermCreationParams {
    interface Raw {
        name: string;
        description: string;
        synonyms?: string[] | null;
    }
}
