/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { LegacyGuidelineConnectionUpdateParams } from "./LegacyGuidelineConnectionUpdateParams";
import { GuidelineToolAssociationUpdateParams } from "./GuidelineToolAssociationUpdateParams";
export declare const LegacyGuidelineUpdateParams: core.serialization.ObjectSchema<serializers.LegacyGuidelineUpdateParams.Raw, Parlant.LegacyGuidelineUpdateParams>;
export declare namespace LegacyGuidelineUpdateParams {
    interface Raw {
        connections?: LegacyGuidelineConnectionUpdateParams.Raw | null;
        tool_associations?: GuidelineToolAssociationUpdateParams.Raw | null;
        enabled?: boolean | null;
    }
}
