/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { LegacyGuideline } from "./LegacyGuideline";
import { LegacyGuidelineConnection } from "./LegacyGuidelineConnection";
import { GuidelineToolAssociation } from "./GuidelineToolAssociation";
export declare const LegacyGuidelineWithConnectionsAndToolAssociations: core.serialization.ObjectSchema<serializers.LegacyGuidelineWithConnectionsAndToolAssociations.Raw, Parlant.LegacyGuidelineWithConnectionsAndToolAssociations>;
export declare namespace LegacyGuidelineWithConnectionsAndToolAssociations {
    interface Raw {
        guideline: LegacyGuideline.Raw;
        connections: LegacyGuidelineConnection.Raw[];
        tool_associations: GuidelineToolAssociation.Raw[];
    }
}
