/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { LegacyPayload } from "./LegacyPayload";
export declare const LegacyEvaluationCreationParams: core.serialization.ObjectSchema<serializers.LegacyEvaluationCreationParams.Raw, Parlant.LegacyEvaluationCreationParams>;
export declare namespace LegacyEvaluationCreationParams {
    interface Raw {
        agent_id: string;
        payloads: LegacyPayload.Raw[];
    }
}
