/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const LegacyTerm: core.serialization.ObjectSchema<serializers.LegacyTerm.Raw, Parlant.LegacyTerm>;
export declare namespace LegacyTerm {
    interface Raw {
        id: string;
        name: string;
        description: string;
        synonyms?: string[] | null;
    }
}
