/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolId } from "./ToolId";
export declare const LegacyContextVariableUpdateParams: core.serialization.ObjectSchema<serializers.LegacyContextVariableUpdateParams.Raw, Parlant.LegacyContextVariableUpdateParams>;
export declare namespace LegacyContextVariableUpdateParams {
    interface Raw {
        name?: string | null;
        description?: string | null;
        tool_id?: ToolId.Raw | null;
        freshness_rules?: string | null;
    }
}
