/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { LegacyPayload } from "./LegacyPayload";
import { LegacyInvoiceData } from "./LegacyInvoiceData";
export declare const LegacyInvoice: core.serialization.ObjectSchema<serializers.LegacyInvoice.Raw, Parlant.LegacyInvoice>;
export declare namespace LegacyInvoice {
    interface Raw {
        payload: LegacyPayload.Raw;
        checksum: string;
        approved: boolean;
        data?: LegacyInvoiceData.Raw | null;
        error?: string | null;
    }
}
