/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const LegacyTermUpdateParams: core.serialization.ObjectSchema<serializers.LegacyTermUpdateParams.Raw, Parlant.LegacyTermUpdateParams>;
export declare namespace LegacyTermUpdateParams {
    interface Raw {
        name?: string | null;
        description?: string | null;
        synonyms?: string[] | null;
    }
}
