/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Session } from "./Session";
export declare const ListSessionsResponse: core.serialization.ObjectSchema<serializers.ListSessionsResponse.Raw, Parlant.ListSessionsResponse>;
export declare namespace ListSessionsResponse {
    interface Raw {
        sessions: Session.Raw[];
    }
}
