/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Event } from "./Event";
export declare const ListEventsResponse: core.serialization.ObjectSchema<serializers.ListEventsResponse.Raw, Parlant.ListEventsResponse>;
export declare namespace ListEventsResponse {
    interface Raw {
        session_id: string;
        events: Event.Raw[];
    }
}
