/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { GuidelineProposition } from "./GuidelineProposition";
import { ToolCall } from "./ToolCall";
import { Term } from "./Term";
import { ContextVariableAndValue } from "./ContextVariableAndValue";
export declare const PreparationIteration: core.serialization.ObjectSchema<serializers.PreparationIteration.Raw, Parlant.PreparationIteration>;
export declare namespace PreparationIteration {
    interface Raw {
        guideline_propositions: GuidelineProposition.Raw[];
        tool_calls: ToolCall.Raw[];
        terms: Term.Raw[];
        context_variables: ContextVariableAndValue.Raw[];
    }
}
