/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { PreparationIterationGenerations } from "./PreparationIterationGenerations";
import { GuidelineProposition } from "./GuidelineProposition";
import { ToolCall } from "./ToolCall";
import { Term } from "./Term";
import { ContextVariableAndValue } from "./ContextVariableAndValue";
export const PreparationIteration = core.serialization.object({
    generations: PreparationIterationGenerations,
    guidelinePropositions: core.serialization.property("guideline_propositions", core.serialization.list(GuidelineProposition)),
    toolCalls: core.serialization.property("tool_calls", core.serialization.list(ToolCall)),
    terms: core.serialization.list(Term),
    contextVariables: core.serialization.property("context_variables", core.serialization.list(ContextVariableAndValue)),
});
