/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const PreparationIterationTerm: core.serialization.ObjectSchema<serializers.PreparationIterationTerm.Raw, Parlant.PreparationIterationTerm>;
export declare namespace PreparationIterationTerm {
    interface Raw {
        id: string;
        name: string;
        description: string;
        synonyms?: string[] | null;
    }
}
