/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { PreparationIterationGenerations } from "./PreparationIterationGenerations";
import { GuidelineMatch } from "./GuidelineMatch";
import { ToolCall } from "./ToolCall";
import { PreparationIterationTerm } from "./PreparationIterationTerm";
import { ContextVariableAndValue } from "./ContextVariableAndValue";
export declare const PreparationIteration: core.serialization.ObjectSchema<serializers.PreparationIteration.Raw, Parlant.PreparationIteration>;
export declare namespace PreparationIteration {
    interface Raw {
        generations: PreparationIterationGenerations.Raw;
        guideline_matches: GuidelineMatch.Raw[];
        tool_calls: ToolCall.Raw[];
        terms: PreparationIterationTerm.Raw[];
        context_variables: ContextVariableAndValue.Raw[];
    }
}
