/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Rule } from "./Rule";
import { Group } from "./Group";
import { Tool } from "./Tool";
import { RelationshipKindDto } from "./RelationshipKindDto";
export declare const Relationship: core.serialization.ObjectSchema<serializers.Relationship.Raw, Parlant.Relationship>;
export declare namespace Relationship {
    interface Raw {
        id: string;
        source_rule?: Rule.Raw | null;
        source_group?: Group.Raw | null;
        target_rule?: Rule.Raw | null;
        target_group?: Group.Raw | null;
        source_tool?: Tool.Raw | null;
        target_tool?: Tool.Raw | null;
        kind: RelationshipKindDto.Raw;
        group_id?: string | null;
    }
}
