/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Guideline } from "./Guideline";
import { Tag } from "./Tag";
import { GuidelineRelationshipKindDto } from "./GuidelineRelationshipKindDto";
export declare const Relationship: core.serialization.ObjectSchema<serializers.Relationship.Raw, Parlant.Relationship>;
export declare namespace Relationship {
    interface Raw {
        id: string;
        source_guideline?: Guideline.Raw | null;
        source_tag?: Tag.Raw | null;
        target_guideline?: Guideline.Raw | null;
        target_tag?: Tag.Raw | null;
        indirect: boolean;
        kind: GuidelineRelationshipKindDto.Raw;
    }
}
