/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { CreateSdkServiceRequest } from "./CreateSdkServiceRequest";
import { CreateOpenApiServiceRequest } from "./CreateOpenApiServiceRequest";
export declare const Request: core.serialization.Schema<serializers.Request.Raw, Parlant.Request>;
export declare namespace Request {
    type Raw = CreateSdkServiceRequest.Raw | CreateOpenApiServiceRequest.Raw;
}
