/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Rule } from "./Rule";
import { Relationship } from "./Relationship";
import { RuleToolAssociation } from "./RuleToolAssociation";
export declare const RuleWithRelationshipsAndToolAssociations: core.serialization.ObjectSchema<serializers.RuleWithRelationshipsAndToolAssociations.Raw, Parlant.RuleWithRelationshipsAndToolAssociations>;
export declare namespace RuleWithRelationshipsAndToolAssociations {
    interface Raw {
        rule: Rule.Raw;
        relationships: Relationship.Raw[];
        tool_associations: RuleToolAssociation.Raw[];
    }
}
