/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { CriticalityDto } from "./CriticalityDto";
import { CompositionModeDto } from "./CompositionModeDto";
import { EffortDto } from "./EffortDto";
export declare const Rule: core.serialization.ObjectSchema<serializers.Rule.Raw, Parlant.Rule>;
export declare namespace Rule {
    interface Raw {
        id: string;
        condition: string;
        action?: string | null;
        description?: string | null;
        title?: string | null;
        criticality?: CriticalityDto.Raw | null;
        enabled?: boolean | null;
        groups: string[];
        metadata: Record<string, unknown>;
        modified_utc: string;
        composition_mode?: CompositionModeDto.Raw | null;
        effort?: EffortDto.Raw | null;
        track?: boolean | null;
        labels?: string[] | null;
        priority?: number | null;
        signals?: string[] | null;
        anti_signals?: string[] | null;
    }
}
