/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { Service } from "./Service";
export declare const ServiceListResponse: core.serialization.ObjectSchema<serializers.ServiceListResponse.Raw, Parlant.ServiceListResponse>;
export declare namespace ServiceListResponse {
    interface Raw {
        services: Service.Raw[];
    }
}
