/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const TermGroupsUpdateParams: core.serialization.ObjectSchema<serializers.TermGroupsUpdateParams.Raw, Parlant.TermGroupsUpdateParams>;
export declare namespace TermGroupsUpdateParams {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
