/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const ToolResult = core.serialization.object({
    data: core.serialization.unknown(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});
