/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ToolResult } from "./ToolResult";
export declare const ToolCall: core.serialization.ObjectSchema<serializers.ToolCall.Raw, Parlant.ToolCall>;
export declare namespace ToolCall {
    interface Raw {
        tool_id: string;
        arguments: Record<string, unknown>;
        result: ToolResult.Raw;
    }
}
