/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const ToolParameterTypeDto = core.serialization.enum_(["string", "number", "integer", "boolean"]);
