/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
export const ToolId = core.serialization.object({
    serviceName: core.serialization.property("service_name", core.serialization.string()),
    toolName: core.serialization.property("tool_name", core.serialization.string()),
});
