/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import { ToolParameterTypeDto } from "./ToolParameterTypeDto";
import { ToolParameterDtoEnumItem } from "./ToolParameterDtoEnumItem";
export const ToolParameter = core.serialization.object({
    type: ToolParameterTypeDto,
    description: core.serialization.string().optional(),
    enum: core.serialization.list(ToolParameterDtoEnumItem).optional(),
});
