/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const TrainingStatusDto: core.serialization.Schema<serializers.TrainingStatusDto.Raw, Parlant.TrainingStatusDto>;
export declare namespace TrainingStatusDto {
    type Raw = "pending" | "running" | "completed" | "failed";
}
