/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const TrainingCreationParams: core.serialization.ObjectSchema<serializers.TrainingCreationParams.Raw, Parlant.TrainingCreationParams>;
export declare namespace TrainingCreationParams {
    interface Raw {
        agent_ids?: string[] | null;
    }
}
