/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
import { ContextVariableValue } from "./ContextVariableValue";
export declare const UpdateContextVariableValueResponse: core.serialization.ObjectSchema<serializers.UpdateContextVariableValueResponse.Raw, Parlant.UpdateContextVariableValueResponse>;
export declare namespace UpdateContextVariableValueResponse {
    interface Raw {
        context_variable_value: ContextVariableValue.Raw;
    }
}
