/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const UpdateContextVariableValueRequestDataItem: core.serialization.Schema<serializers.UpdateContextVariableValueRequestDataItem.Raw, Parlant.UpdateContextVariableValueRequestDataItem>;
export declare namespace UpdateContextVariableValueRequestDataItem {
    type Raw = string | number | number | boolean;
}
