/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Parlant from "../../api/index";
import * as core from "../../core";
export declare const UtteranceReasonDto: core.serialization.Schema<serializers.UtteranceReasonDto.Raw, Parlant.UtteranceReasonDto>;
export declare namespace UtteranceReasonDto {
    type Raw = "buy_time" | "follow_up";
}
