/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         agentId: "a1g2e3n4t5",
 *         payloads: [{
 *                 kind: "guideline",
 *                 guideline: {
 *                     content: {
 *                         condition: "when customer asks about pricing",
 *                         action: "provide current pricing information"
 *                     },
 *                     operation: "add",
 *                     coherenceCheck: true,
 *                     connectionProposition: true
 *                 }
 *             }]
 *     }
 */
export interface EvaluationCreationParams {
    /** Unique identifier for the agent */
    agentId: string;
    payloads: Parlant.Payload[];
}
