/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         agentId: "a1g2e3n4t5",
 *         payloads: [{
 *                 kind: "rule",
 *                 rule: {
 *                     content: {
 *                         condition: "when customer asks about pricing"
 *                     },
 *                     toolIds: [{
 *                             serviceName: "email_service",
 *                             toolName: "send_email"
 *                         }],
 *                     operation: "add",
 *                     actionProposition: true
 *                 }
 *             }]
 *     }
 */
export interface EvaluationCreationParams {
    /** Agent context to use when evaluating agent-dependent propositions such as rule signals. */
    agentId?: string;
    payloads: Parlant.Payload[];
}
