/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CustomerCreationParams {
    name: string;
    extra?: Record<string, string | undefined>;
}
