/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         name: "Scooby",
 *         groups: {
 *             add: ["t9a8g703f4", "group_456abc"],
 *             remove: ["group_789def", "group_012ghi"]
 *         }
 *     }
 */
export interface CustomerUpdateParams {
    /** An arbitrary string that identifies and/or describes the customer */
    name?: string;
    metadata?: Parlant.CustomerMetadataUpdateParams;
    groups?: Parlant.CustomerGroupUpdateParams;
}
