/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { GuidelineRelationshipKindDto } from "../../../../types/GuidelineRelationshipKindDto";
export declare const RelationshipCreationParams: core.serialization.Schema<serializers.RelationshipCreationParams.Raw, Parlant.RelationshipCreationParams>;
export declare namespace RelationshipCreationParams {
    interface Raw {
        source_guideline?: string | null;
        source_tag?: string | null;
        target_guideline?: string | null;
        target_tag?: string | null;
        kind: GuidelineRelationshipKindDto.Raw;
    }
}
