/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         name: "name",
 *         description: "description"
 *     }
 */
export interface TermCreationParams {
    name: string;
    description: string;
    synonyms?: string[];
}
