/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface TermUpdateParams {
    name?: string;
    description?: string;
    synonyms?: string[];
}
