/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { Customer } from "../../../types/Customer";
export const Response = core.serialization.list(Customer);
