/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Customer } from "../../../types/Customer";
export declare const Response: core.serialization.Schema<serializers.customers.list.Response.Raw, Parlant.Customer[]>;
export declare namespace Response {
    type Raw = Customer.Raw[];
}
