/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const CreateTagRequest: core.serialization.Schema<serializers.CreateTagRequest.Raw, Parlant.CreateTagRequest>;
export declare namespace CreateTagRequest {
    interface Raw {
        name: string;
    }
}
