/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Guidelines {
    interface Options {
        environment: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}
export declare class Guidelines {
    protected readonly _options: Guidelines.Options;
    constructor(_options: Guidelines.Options);
    /**
     * Lists all guidelines for the specified tag or all guidelines if no tag is provided.
     *
     * Returns an empty list if no guidelines exist.
     * Guidelines are returned in no guaranteed order.
     * Does not include connections or tool associations.
     *
     * @param {Parlant.GuidelinesListRequest} request
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.list()
     */
    list(request?: Parlant.GuidelinesListRequest, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.Guideline[]>;
    /**
     * Creates a new guideline.
     *
     * See the [documentation](https://parlant.io/docs/concepts/customization/guidelines) for more information.
     *
     * @param {Parlant.GuidelineCreationParams} request
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.create({
     *         condition: "when the customer asks about pricing",
     *         action: "provide current pricing information and mention any ongoing promotions",
     *         enabled: false
     *     })
     */
    create(request: Parlant.GuidelineCreationParams, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.Guideline>;
    /**
     * Retrieves a specific guideline with all its connections and tool associations.
     *
     * Returns both direct and indirect connections between guidelines.
     * Tool associations indicate which tools the guideline can use.
     *
     * @param {string} guidelineId - Unique identifier for the guideline
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.retrieve("IUCGT-l4pS")
     */
    retrieve(guidelineId: string, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.GuidelineWithConnectionsAndToolAssociations>;
    /**
     * @param {string} guidelineId - Unique identifier for the guideline
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.delete("IUCGT-l4pS")
     */
    delete(guidelineId: string, requestOptions?: Guidelines.RequestOptions): Promise<void>;
    /**
     * Updates a guideline's connections and tool associations.
     *
     * Only provided attributes will be updated; others remain unchanged.
     *
     * Connection rules:
     * - A guideline cannot connect to itself
     * - Only direct connections can be removed
     * - The connection must specify this guideline as source or target
     *
     * Tool Association rules:
     * - Tool services and tools must exist before creating associations
     *
     * @param {string} guidelineId - Unique identifier for the guideline
     * @param {Parlant.GuidelineUpdateParams} request
     * @param {Guidelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.guidelines.update("IUCGT-l4pS", {
     *         connections: {
     *             add: [{
     *                     source: "guide_123xyz",
     *                     target: "guide_789xyz"
     *                 }],
     *             remove: ["guide_456xyz"]
     *         },
     *         toolAssociations: {
     *             add: [{
     *                     serviceName: "pricing_service",
     *                     toolName: "get_prices"
     *                 }],
     *             remove: [{
     *                     serviceName: "old_service",
     *                     toolName: "old_tool"
     *                 }]
     *         },
     *         enabled: true
     *     })
     */
    update(guidelineId: string, request?: Parlant.GuidelineUpdateParams, requestOptions?: Guidelines.RequestOptions): Promise<Parlant.GuidelineWithConnectionsAndToolAssociations>;
}
