/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Glossary {
    interface Options {
        environment: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}
export declare class Glossary {
    protected readonly _options: Glossary.Options;
    constructor(_options: Glossary.Options);
    /**
     * @param {string} agentId
     * @param {Glossary.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.glossary.listTerms("agent_id")
     */
    listTerms(agentId: string, requestOptions?: Glossary.RequestOptions): Promise<Parlant.TermListResponse>;
    /**
     * @param {string} agentId
     * @param {Parlant.TermCreationParams} request
     * @param {Glossary.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.glossary.createTerm("agent_id", {
     *         name: "name",
     *         description: "description"
     *     })
     */
    createTerm(agentId: string, request: Parlant.TermCreationParams, requestOptions?: Glossary.RequestOptions): Promise<Parlant.CreateTermResponse>;
    /**
     * @param {string} agentId
     * @param {string} termId
     * @param {Glossary.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.glossary.retrieveTerm("agent_id", "term_id")
     */
    retrieveTerm(agentId: string, termId: string, requestOptions?: Glossary.RequestOptions): Promise<Parlant.Term>;
    /**
     * @param {string} agentId
     * @param {string} termId
     * @param {Glossary.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.glossary.deleteTerm("agent_id", "term_id")
     */
    deleteTerm(agentId: string, termId: string, requestOptions?: Glossary.RequestOptions): Promise<Parlant.TermDeletionResponse>;
    /**
     * @param {string} agentId
     * @param {string} termId
     * @param {Parlant.TermUpdateParams} request
     * @param {Glossary.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.glossary.updateTerm("agent_id", "term_id")
     */
    updateTerm(agentId: string, termId: string, request?: Parlant.TermUpdateParams, requestOptions?: Glossary.RequestOptions): Promise<Parlant.Term>;
}
