/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
import { UtteranceField } from "../../../../types/UtteranceField";
export declare const UtteranceCreationParams: core.serialization.Schema<serializers.UtteranceCreationParams.Raw, Parlant.UtteranceCreationParams>;
export declare namespace UtteranceCreationParams {
    interface Raw {
        value: string;
        fields: UtteranceField.Raw[];
        tags?: string[] | null;
    }
}
