/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Rule } from "../../../types/Rule";
export declare const Response: core.serialization.Schema<serializers.rules.list.Response.Raw, Parlant.Rule[]>;
export declare namespace Response {
    type Raw = Rule.Raw[];
}
