/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Utterances {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Utterances {
    protected readonly _options: Utterances.Options;
    constructor(_options: Utterances.Options);
    /**
     * @param {Parlant.UtterancesListRequest} request
     * @param {Utterances.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.utterances.list()
     */
    list(request?: Parlant.UtterancesListRequest, requestOptions?: Utterances.RequestOptions): Promise<Parlant.Utterance[]>;
    /**
     * @param {Parlant.UtteranceCreationParams} request
     * @param {Utterances.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.utterances.create({
     *         value: "Your account balance is {balance}",
     *         fields: [{
     *                 name: "balance",
     *                 description: "Account's balance",
     *                 examples: ["9000"]
     *             }]
     *     })
     */
    create(request: Parlant.UtteranceCreationParams, requestOptions?: Utterances.RequestOptions): Promise<Parlant.Utterance>;
    /**
     * Retrieves details of a specific utterance by ID.
     *
     * @param {string} utteranceId
     * @param {Utterances.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.utterances.retrieve("t9a8g703f4")
     */
    retrieve(utteranceId: string, requestOptions?: Utterances.RequestOptions): Promise<Parlant.Utterance>;
    /**
     * @param {string} utteranceId
     * @param {Utterances.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.utterances.delete("t9a8g703f4")
     */
    delete(utteranceId: string, requestOptions?: Utterances.RequestOptions): Promise<void>;
    /**
     * Updates an existing utterance's attributes.
     *
     * Only provided attributes will be updated; others remain unchanged.
     * The utterance's ID and creation timestamp cannot be modified.
     * Extra metadata and tags can be added or removed independently.
     *
     * @param {string} utteranceId
     * @param {Parlant.UtteranceUpdateParams} request
     * @param {Utterances.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.utterances.update("t9a8g703f4", {
     *         value: "Your updated balance is {balance}",
     *         fields: [{
     *                 name: "balance",
     *                 description: "Updated account balance",
     *                 examples: ["10000"]
     *             }]
     *     })
     */
    update(utteranceId: string, request?: Parlant.UtteranceUpdateParams, requestOptions?: Utterances.RequestOptions): Promise<Parlant.Utterance>;
}
