/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Parlant from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const JourneyCreationParams: core.serialization.Schema<serializers.JourneyCreationParams.Raw, Parlant.JourneyCreationParams>;
export declare namespace JourneyCreationParams {
    interface Raw {
        title: string;
        description: string;
        conditions: string[];
        tags?: string[] | null;
    }
}
