/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import { Service } from "../../../types/Service";
export const Response = core.serialization.list(Service);
