/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Parlant from "../../../../api/index";
import * as core from "../../../../core";
import { Utterance } from "../../../types/Utterance";
export declare const Response: core.serialization.Schema<serializers.utterances.list.Response.Raw, Parlant.Utterance[]>;
export declare namespace Response {
    type Raw = Utterance.Raw[];
}
