/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Parlant from "../../../../index";
/**
 * @example
 *     {
 *         name: "UserBalance",
 *         description: "Stores the account balances of users",
 *         toolId: {
 *             serviceName: "finance_service",
 *             toolName: "balance_checker"
 *         },
 *         freshnessRules: {
 *             months: [1, 6, 12],
 *             daysOfMonth: [1, 15, 30],
 *             daysOfWeek: ["Monday", "Wednesday", "Friday"],
 *             hours: [9, 13, 17],
 *             minutes: [0, 30],
 *             seconds: [0, 30]
 *         }
 *     }
 */
export interface ContextVariableCreationParams {
    /** Name of the context variable */
    name: string;
    /** Description of the context variable's purpose */
    description?: string;
    toolId?: Parlant.ToolId;
    /** Rules for data freshness validation */
    freshnessRules?: Parlant.FreshnessRules;
}
