/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Fragments {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Fragments {
    protected readonly _options: Fragments.Options;
    constructor(_options: Fragments.Options);
    /**
     * @param {Parlant.FragmentsListRequest} request
     * @param {Fragments.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.fragments.list()
     */
    list(request?: Parlant.FragmentsListRequest, requestOptions?: Fragments.RequestOptions): Promise<Parlant.Fragment[]>;
    /**
     * @param {Parlant.FragmentCreationParams} request
     * @param {Fragments.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.fragments.create({
     *         value: "Your account balance is {balance}",
     *         fields: [{
     *                 name: "balance",
     *                 description: "Account's balance",
     *                 examples: ["9000"]
     *             }]
     *     })
     */
    create(request: Parlant.FragmentCreationParams, requestOptions?: Fragments.RequestOptions): Promise<Parlant.Fragment>;
    /**
     * Retrieves details of a specific fragment by ID.
     *
     * @param {string} fragmentId
     * @param {Fragments.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.fragments.retrieve("t9a8g703f4")
     */
    retrieve(fragmentId: string, requestOptions?: Fragments.RequestOptions): Promise<Parlant.Fragment>;
    /**
     * @param {string} fragmentId
     * @param {Fragments.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.fragments.delete("t9a8g703f4")
     */
    delete(fragmentId: string, requestOptions?: Fragments.RequestOptions): Promise<void>;
    /**
     * Updates an existing fragment's attributes.
     *
     * Only provided attributes will be updated; others remain unchanged.
     * The fragment's ID and creation timestamp cannot be modified.
     * Extra metadata and tags can be added or removed independently.
     *
     * @param {string} fragmentId
     * @param {Parlant.FragmentUpdateParams} request
     * @param {Fragments.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.fragments.update("t9a8g703f4", {
     *         value: "Your updated balance is {balance}",
     *         fields: [{
     *                 name: "balance",
     *                 description: "Updated account balance",
     *                 examples: ["10000"]
     *             }]
     *     })
     */
    update(fragmentId: string, request?: Parlant.FragmentUpdateParams, requestOptions?: Fragments.RequestOptions): Promise<Parlant.Fragment>;
}
