/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as Parlant from "../../../index";
export declare namespace Groups {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Groups {
    protected readonly _options: Groups.Options;
    constructor(_options: Groups.Options);
    /**
     * Lists all groups in the system, optionally filtered by name.
     *
     * Returns an empty list if no groups exist or none match the filter.
     * Groups are returned in no particular order.
     *
     * @param {Parlant.GroupsListRequest} request
     * @param {Groups.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.groups.list()
     */
    list(request?: Parlant.GroupsListRequest, requestOptions?: Groups.RequestOptions): Promise<Parlant.Group[]>;
    /**
     * Creates a new group with the specified name.
     *
     * The group ID is automatically generated and the creation timestamp is set to the current time.
     * Group names must be unique and follow the kebab-case format.
     *
     * @param {Parlant.GroupCreationParams} request
     * @param {Groups.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.groups.create({
     *         name: "premium-customer"
     *     })
     */
    create(request: Parlant.GroupCreationParams, requestOptions?: Groups.RequestOptions): Promise<Parlant.Group>;
    /**
     * Retrieves details of a specific group by ID.
     *
     * Returns a 404 error if no group exists with the specified ID.
     *
     * @param {string} groupId - Unique identifier for the group to operate on
     * @param {Groups.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.groups.retrieve("group_123xyz")
     */
    retrieve(groupId: string, requestOptions?: Groups.RequestOptions): Promise<Parlant.Group>;
    /**
     * Permanently deletes a group.
     *
     * This operation cannot be undone. Returns a 404 error if no group exists with the specified ID.
     * Note that deleting a group does not affect resources that were previously grouped with it.
     *
     * @param {string} groupId
     * @param {Groups.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.groups.delete("group_id")
     */
    delete(groupId: string, requestOptions?: Groups.RequestOptions): Promise<void>;
    /**
     * Updates an existing group's name.
     *
     * Only the name can be modified,
     * The group's ID and creation timestamp cannot be modified.
     *
     * @param {string} groupId - Unique identifier for the group to operate on
     * @param {Parlant.GroupUpdateParams} request
     * @param {Groups.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Parlant.NotFoundError}
     * @throws {@link Parlant.UnprocessableEntityError}
     *
     * @example
     *     await client.groups.update("group_123xyz", {
     *         name: "enterprise-customer"
     *     })
     */
    update(groupId: string, request: Parlant.GroupUpdateParams, requestOptions?: Groups.RequestOptions): Promise<Parlant.Group>;
}
